/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ElevatorControl;
import form.ElevatorButton;
import javax.swing.JLabel;

/**
 *
 * @author Thibaut
 */
public class CabinView extends javax.swing.JPanel 
{
    private ElevatorControl control;
    /**
     * Creates new form CabinView
     */
    public CabinView() {}
    
    public void init(ElevatorControl control)
    {
        this.control = control;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        StairsDisplay = new javax.swing.JLabel();
        ThirdButton = new ElevatorButton("3", "/images/Three.png", "/images/ThreeSelected.png", this.control);
        SecondButton = new ElevatorButton("2", "/images/Two.png", "/images/TwoSelected.png", this.control);
        FirstButton = new ElevatorButton("1", "/images/One.png", "/images/OneSelected.png", this.control) ;
        ZeroButton = new ElevatorButton("0", "/images/Zero.png", "/images/ZeroSelected.png", this.control);

        setLayout(null);

        Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Cabine");
        add(Title);
        Title.setBounds(158, 23, 68, 30);
        add(StairsDisplay);
        StairsDisplay.setBounds(45, 71, 50, 29);
        add(ThirdButton);
        ThirdButton.setBounds(45, 106, 50, 50);
        add(SecondButton);
        SecondButton.setBounds(45, 162, 50, 50);
        add(FirstButton);
        FirstButton.setBounds(45, 223, 50, 50);
        add(ZeroButton);
        ZeroButton.setBounds(45, 284, 50, 50);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FirstButton;
    private javax.swing.JButton SecondButton;
    private javax.swing.JLabel StairsDisplay;
    private javax.swing.JButton ThirdButton;
    private javax.swing.JLabel Title;
    private javax.swing.JButton ZeroButton;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.JButton getButton(String name)
    {
        if(name.equals("3"))
            return this.ThirdButton;
        else if(name.equals("2"))
            return this.SecondButton;
        else if(name.equals("1"))
            return this.FirstButton;
        else if(name.equals("0"))
            return this.ZeroButton;
        else
            return null;
    }

    public JLabel getStairsDisplay() {
        return StairsDisplay;
    }
    
}
