/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ElevatorControl;
import form.ElevatorButton;

/**
 *
 * @author Thibaut
 */
public class ElevatorView extends javax.swing.JPanel 
{
    private ElevatorControl control;
    
    /**
     * Creates new form ElevatorView
     */
    public ElevatorView() {}
    
    public void init(ElevatorControl control)
    {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThirdButton = new ElevatorButton("3", "/images/Call.png", "/images/CallSelected.png", this.control);
        SecondButton = new ElevatorButton("2", "/images/Call.png", "/images/CallSelected.png", this.control);
        FirstButton = new ElevatorButton("1", "/images/Call.png", "/images/CallSelected.png", this.control) ;
        ZeroButton = new ElevatorButton("0", "/images/Call.png", "/images/CallSelected.png", this.control);

        setLayout(null);
        add(ThirdButton);
        ThirdButton.setBounds(160, 110, 50, 50);
        add(SecondButton);
        SecondButton.setBounds(160, 170, 50, 50);
        add(FirstButton);
        FirstButton.setBounds(160, 230, 50, 50);
        add(ZeroButton);
        ZeroButton.setBounds(160, 290, 50, 50);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FirstButton;
    private javax.swing.JButton SecondButton;
    private javax.swing.JButton ThirdButton;
    private javax.swing.JButton ZeroButton;
    // End of variables declaration//GEN-END:variables
}
